### ISSUE TITLE
Fix up path splitter to get it working well on Linux

### ISSUE THREAD

**Issue by tcjj3** [sam210723/himawari-rx#5]
Hello Sam,
I'm testing this decoder on Linux today, and I found the path splitter is **`\\`** in **file.py**, it's not working well on Linux.
But I found the path splitter is **`/`** in **products.py** on **xrit-rx**, and I modified it for **himawari-rx** and tested again, then I found it works well on both Windows and Linux.
So I suggest to replace the path splitter from **`\\`** to **`/`**, then it can work on both Windows and Linux.
Thanks again!

**Comment by tcjj3** [comment]
The problem are also happended in `/tools/xrit-img.py` and `/tools/false-colour.py`.

**Comment by sam210723** [comment]
Hi Chaojun,

Thanks for pointing this out. I've fixed this in all three files. Patch v0.1.2 is now available.

Thank you also for your testing over in issue #2 and in your himawari-rx_auto_scripts repository.
I will try to improve himawari-rx based on your work.

Thanks!
Sam.
