### ISSUE TITLE
Received folder structure

### ISSUE THREAD

**Issue by backer80** [sam210723/himawari-rx#8]
Thanks for much for himawari-rx. I am using it with my TBS6903 PCIE card / Win 10. 
I also had issues with TSduck and incomplete files but i added "-P regulate --bitrate 3000000" and it seems to be stable now.

I use xrit2pic to view/convert the images. Since Himawari-rx saves them in separate folder, I don't know how to easy combine them into one large folder. This is so I can see see multiple images/create movies easily without manually combining them all.  

It does work one at a time if i manually select the image receive folder. 
It would be great if there was an option to this with himawari-rx that would save all images in the single folder?

**Comment by sam210723** [comment]
Thanks for using himawari-rx! I've just pushed [himawari-rx `v0.1.3`](https://github.com/sam210723/himawari-rx/releases/tag/v0.1.3) which has a new option called `combine` in the configuration file.

By default it is set to `false`. When set to `true`, all images will be saved into either a `LRIT` or `HRIT` folder.
Low-resolution images in the `LRIT` folder, high-resolution images in the `HRIT` folder.

![XRIT2PIC](https://user-images.githubusercontent.com/5117093/131250213-bc3034a3-6ecf-44c1-82d4-4e95de83e7b3.jpg)

Let me know if you have any issues.

**Comment by backer80** [comment]
Hi Sam,
Thank you so much for making this change. Works well.
I am sure there were many other ways of doing it but this is easy for me.
